### ISSUE TITLE
Bug in your eksctl project (issues disabled there?)

### ISSUE THREAD

**Issue by trauts2** [spotinst/spotctl#3]
**What happened**:
Error received:
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[✖]  Custom::ocean/NodeGroup: CREATE_FAILED – "Failed to create resource. ocean create failed: ValidationError: \"5\" must be one of [g4dn.xlarge, g4dn.8xlarge, g4dn.4xlarge, g4dn.2xlarge, g4dn.16xlarge, g4dn.12xlarge, t3a.xlarge, t3a.small, t3a.nano, t3a.micro, t3a.medium, t3a.large, t3a.2xlarge, r5ad.xlarge, r5ad.large, r5ad.8xlarge, r5ad.4xlarge, r5ad.2xlarge, r5ad.24xlarge, r5ad.16xlarge, r5ad.12xlarge, r5a.xlarge, r5a.large, r5a.8xlarge, r5a.4xlarge, r5a.2xlarge, r5a.24xlarge, r5a.16xlarge, r5a.12xlarge, r5.xlarge, r5.metal, r5.large, r5.8xlarge, r5.4xlarge, r5.2xlarge, r5.24xlarge, r5.16xlarge, r5.12xlarge, m5ad.xlarge, m5ad.large, m5ad.8xlarge, m5ad.4xlarge, m5ad.2xlarge, m5ad.24xlarge, m5ad.16xlarge, m5ad.12xlarge, m5a.xlarge, m5a.large, m5a.8xlarge, m5a.4xlarge, m5a.2xlarge, m5a.24xlarge, m5a.16xlarge, m5a.12xlarge, z1d.xlarge, z1d.metal, z1d.large, z1d.6xlarge, z1d.3xlarge, z1d.2xlarge, z1d.12xlarge, x1e.xlarge, x1e.8xlarge, x1e.4xlarge, x1e.32xlarge, x1e.2xlarge, x1e.16xlarge, t3.xlarge, t3.small, t3.nano, t3.micro, t3.medium, t3.large, t3.2xlarg"

**What you expected to happen**:

I can create a cluster using standard eksctl, it is the spotinst extensions where I see the issue

**How to reproduce it (as minimally and precisely as possible):**

Here's my config file

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-eks-spotinst
  region: us-east-1
  version: '1.15'
  tags:
    creator: stu
    environment: test-eks-spotinst
cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager"]
nodeGroups:
  - name: standard-workers
    volumeSize: 16 
    labels: 
      role: workers
    privateNetworking: true
    tags: 
      role: eks-workers
      environment: test
      customer: fh
    spotOcean:
      strategy:
        # Percentage of Spot instances that would spin up from the desired 
        # capacity.
        spotPercentage: 100
        # Allow Ocean to utilize any available reserved instances first before 
        # purchasing Spot instances.
        utilizeReservedInstances: true
        # Launch On-Demand instances in case of no Spot instances available.
        fallbackToOd: true
      autoScaler:
        # Enable the Ocean autoscaler. 
        enabled: true
        # Cooldown period between scaling actions.
        cooldown: 300
        # Spare resource capacity management enabling fast assignment of Pods 
        # without waiting for new resources to launch.
        headrooms:
            # Number of CPUs to allocate. CPUs are denoted in millicores, where 
            # 1000 millicores = 1 vCPU.
          - cpuPerUnit: 2
            # Number of GPUs to allocate.
            gpuPerUnit: 0
            # Amount of memory (MB) to allocate.
            memoryPerUnit: 2048
            # Number of units to retain as headroom, where each unit has the 
            # defined CPU and memory.
            numOfUnits: 1
      compute:
        instanceTypes:
          # Instance types allowed in the Ocean cluster. Cannot be configured 
          # if the blacklist is configured.
          whitelist: # OR blacklist
            - m5a.large
            - m5a.xlarge
            - m5a.2xlarge
            - m5.large
            - m5.xlarge
            - m5.x2large
            - m4.large
            - m4.xlarge
            - m4.x2large
            - c5.large
            - c5.xlarge  
            - c5.2xlarge  
            - c5.4xlarge  
            - c4.large
            - c4.xlarge  
            - c4.2xlarge  
            - c4.4xlarge  
            - r5.large
            - r5.xlarge  
            - r5a.large
            - r5a.xlarge  

**Anything else we need to know:**

What is the channel for submitting issues with your fork of eksctl? 

**Environment:**

- CLI version (use `spotinst version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by liranp** [comment]
Hi @trauts2, it seems like a configuration error. Please note that your `whitelist` field contains an invalid instance type (specifically, the sixth is misspelled — `m5.x2large` should be `m5.2xlarge`), hence the error `ValidationError: "5" must be one of ...`. Also, I've enabled the issues on the [spotinst/weaveworks-eksctl](https://github.com/spotinsts/weaveworks-eksctl) project, so thanks for letting us know.

**Comment by trauts2** [comment]
Hi Liran.  Thanks for enabling issues on the eksctl fork.  Is it being monitored?  Here's an issue opened for an advertised feature that doesn't seem to be working as expected.
https://github.com/spotinst/weaveworks-eksctl/issues/1
