### ISSUE TITLE
Error Installing using Homebrew

### ISSUE THREAD

**Issue by ojengwa** [spotinst/spotctl#5]
**What happened**: Installing spotctl via `brew install spotinst/tap/spotctl ` fails with an exception 
`Error: An exception occurred within a child process:
  TypeError: no implicit conversion of Array into Integer`

**What you expected to happen**: Installation should have succeeded 

**How to reproduce it (as minimally and precisely as possible):** `brew install spotinst/tap/spotctl `

**Anything else we need to know:** 

**Environment:**

- CLI version (use `spotinst version`):
- OS (e.g: `cat /etc/os-release`):
ProductName:	macOS
ProductVersion:	11.0
BuildVersion:	20A5384c 
- Kernel (e.g. `uname -a`): Darwin dev.local 20.1.0 Darwin Kernel Version 20.1.0: Thu Sep 24 20:22:06 PDT 2020; root:xnu-7195.40.89.100.3~1/RELEASE_X86_64 x86_64
- Others:
**Homebrew Version**:
Homebrew 2.5.5
Homebrew/homebrew-core (git revision 0213ec; last commit 2020-10-11)
Homebrew/homebrew-cask (no git repository

**Comment by liranp** [comment]
Thank you for bringing this to our attention. The issue has been resolved.
