### ISSUE TITLE
Named Profile management in Spotctl

### ISSUE THREAD

**Issue by YarinPinyan** [spotinst/spotctl#97]
**What would you like to be added?**
Named profile that we could switch the profiles the same that is allowed in AWS CLI

**Why is this needed?**
Sometimes, in a Spot Organization, We're having more than one account that we need to manage, or more than one user that should use the spotctl, the same way that AWS allows us to do; `aws --profile <<PROFILE_NAME>> <<command>> ....`

Unfortunately, when looking for some spotctl profile capabilities, I couldn't find a match that will answer these needs.

As a reference, that's the way it is implemented in AWS:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

**Comment by liranp** [comment]
[Implemented](https://github.com/spotinst/spotctl/blob/v0.20.0/internal/cmd/options/common.go#L90) already (see: `spotctl options`). Usage example:
```
spotctl [command] --profile PROFILE
```
